version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend
hooks:
  BeforeInstall:
      - location: server_configs/scripts/before_install.sh
  AfterInstall:
      - location: server_configs/scripts/after_install.sh
